# Generated by Django 5.2.3 on 2025-07-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
    ]
